name = "Tower Defense Modpack"
author = "mattf"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f28f4260352e2e897a0491a00068ff5ad4be20e5380a767211288b2afeb1f718"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
