name = "Tower Defense Modpack"
author = "mattf"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "761dee020b8feaf65d123c2e96952c4403b721d468ce9dc673479e527c9ede1f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
