name = "Tower Defense Modpack"
author = "mattf"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fea2bc26fb97bbe270d9261b789d5fc76f8b10600759dba117d444fb78e4b04"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
